language: node_js
node_js: node
git:
  depth: 2
  submodules: false
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_7ae5308e2fd2_key -iv $encrypted_7ae5308e2fd2_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'xiazeyu'
- git config --global user.email 'xiazeyu_2011@126.com'
- git submodule update --init --recursive
install:
- npm install
script:
- npm run build:prod && npm run build:esdoc && npm run deploy:doc
