language: node_js
node_js: node
git:
  depth: 2
  submodules: false
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- 'git submodule update --init --recursive'
install:
- 'npm install'
script:
- 'npm run build:prod'
- 'npm run lint'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./build/deployDocs; fi'
